### ISSUE TITLE
Support for custom fields

### ISSUE THREAD

**Issue by mbdavid** [LeviticusMB/bestest_markdown_editor#3]
Hi, nice plugins! Thanks

How could be possible add this markdown editor in custom fields? For custom field type "Long Text" with "Text formatting = true" and "Full width layout = true"

![image](https://user-images.githubusercontent.com/1137197/48257075-a71eac80-e3f8-11e8-8754-34897001968f.png)

![image](https://user-images.githubusercontent.com/1137197/48257253-24e2b800-e3f9-11e8-8cc9-84f4e6794d2d.png)

**Comment by LeviticusMB** [comment]
This editor actually just replaces the `jstoolbar` toolbar, and I know that Redmine does not show this toolbar everywhere it should. Unfortunately, there is nothing I can do about this.

I know Redmine 4.0 changed a few things around the toolbar, so maybe there is a toolbar for custom issue fields now? See https://www.redmine.org/issues/27758 for instance.

I've not upgraded to 4.0 yet though, so I'm not even sure this plugin works with 4.0 yet.
