### ISSUE TITLE
Editor does not show after installation

### ISSUE THREAD

**Issue by favrei** [LeviticusMB/bestest_markdown_editor#4]
Hello,
The editor does not show up as the examples do after installing on our server.
![screenshot_282](https://user-images.githubusercontent.com/17000685/48393027-d14dd280-e748-11e8-9e87-8ec643ff1243.png)

A blank section flashes for the first time I clicked on the editing area before it disappeared, it might have to do with some issue of the editor.
![screenshot_281o](https://user-images.githubusercontent.com/17000685/48393287-e414d700-e749-11e8-8b3a-918cf928ca5a.png)

-------------- these are my system information --------------
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  bestest_markdown_editor        1.1.0
  redmine_agile                  1.4.5
  redmine_checklists             3.1.11
  redmine_ckeditor               1.1.5
  redmineup_tags                 2.0.0

**Comment by LeviticusMB** [comment]
I don't think you can have both `redmine_ckeditor` and this editor at the same time. They would most likely conflict. And this editor only works if you use Markdown as the wiki language anyways.
