### ISSUE TITLE
Can BME work with other plugins

### ISSUE THREAD

**Issue by paulvi** [LeviticusMB/bestest_markdown_editor#6]
Can BME work with other redmine markdown plugins e.g. https://www.redmine.org/plugins/redmine_highlightjs ?

**Comment by LeviticusMB** [comment]
I've not tried it, but I would guess so. `redmine_highlightjs` seems to just modify the rendered result, not the actual editor.

Note that the editor's inline preview would not match the new highlighting/color scheme though.
